# This rule is not used by the project motd-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to motd.howcoldismy.beer resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: motd-operator
    app.kubernetes.io/managed-by: kustomize
  name: motd-viewer-role
rules:
- apiGroups:
  - motd.howcoldismy.beer
  resources:
  - motds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - motd.howcoldismy.beer
  resources:
  - motds/status
  verbs:
  - get
